version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      vpcbr:
        ipv4_address: 10.30.0.30
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/16
